web: gunicorn playto_payout.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 60
worker: celery -A playto_payout worker --loglevel=info --concurrency=2
beat: celery -A playto_payout beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
release: python manage.py migrate --noinput && python seed.py
